### ISSUE TITLE
デザイン作成

### ISSUE THREAD

**Issue by saku-1101** [Matsumae-lab-dev/teamA#13]
[Figma](https://www.figma.com/)を使ってやる！

**Comment by nnnnn81** [comment]
だいたいできた！todo一覧の表示画面だけみんなではなしあい

**Comment by smaru1111** [comment]
## ワイヤーフレーム(大まかなデザイン)
https://www.figma.com/file/zBjlBSaPowcKpUVVKSN4Uo/%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E8%A8%AD%E8%A8%88?type=design&node-id=0%3A1&mode=design&t=hGj2itwZKQe04MpO-1
