### ISSUE TITLE
バックエンド技術選定

### ISSUE THREAD

**Issue by saku-1101** [Matsumae-lab-dev/teamA#7]

**Comment by smaru1111** [comment]
## 技術選定
- golang + gin
- MySQL + [Bun ORM](https://bun.uptrace.dev/)
- Docker(codespaces)

Go言語の[Gin Web Framework](https://gin-gonic.com/ja/)と[Bun ORM](https://bun.uptrace.dev/)を用いてWeb API作成する。
金谷君もバックエンドに参加する可能性もあるため、環境構築が手軽なCodespaces環境を使う。

**Comment by saku-1101** [comment]
- air入れる
