### ISSUE TITLE
フロントエンド技術選定

### ISSUE THREAD

**Issue by saku-1101** [Matsumae-lab-dev/teamA#8]
## フロントエンドとは？？
- 見た目（UI）をいじいじ
- JavaScriptで基本的には開発していく
- バックエンドからAPIを通して受け取ったデータをJavaScriptで加工して画面に反映する

## フロントエンドの開発を始めるために...
- UI決めてく
  - [Figma](https://www.figma.com/)使う

**Comment by smaru1111** [comment]
## 環境
- node.js
- nvm(nodeのバージョン管理)
- React + vite

**Comment by kanegon893** [comment]
フォーム作成：React-hook-form
ルーティング設定：React-router-dom
その後は順次ライブラリを選定
